# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imagemixer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(872, 582)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.comboReal2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboReal2.setObjectName("comboReal2")
        self.comboReal2.addItem("")
        self.comboReal2.addItem("")
        self.comboReal2.addItem("")
        self.comboReal2.addItem("")
        self.gridLayout.addWidget(self.comboReal2, 7, 2, 1, 1)
        self.Slider_2 = QtWidgets.QSlider(self.centralwidget)
        self.Slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_2.setObjectName("Slider_2")
        self.gridLayout.addWidget(self.Slider_2, 8, 0, 1, 1)
        self.comboReal1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboReal1.setObjectName("comboReal1")
        self.comboReal1.addItem("")
        self.comboReal1.addItem("")
        self.comboReal1.addItem("")
        self.comboReal1.addItem("")
        self.gridLayout.addWidget(self.comboReal1, 0, 2, 1, 1)
        self.chaged_img2 = QtWidgets.QLabel(self.centralwidget)
        self.chaged_img2.setText("")
        self.chaged_img2.setObjectName("chaged_img2")
        self.gridLayout.addWidget(self.chaged_img2, 11, 2, 1, 1)
        self.output1 = QtWidgets.QLabel(self.centralwidget)
        self.output1.setText("")
        self.output1.setObjectName("output1")
        self.gridLayout.addWidget(self.output1, 9, 0, 1, 1)
        self.img2 = QtWidgets.QLabel(self.centralwidget)
        self.img2.setText("")
        self.img2.setObjectName("img2")
        self.gridLayout.addWidget(self.img2, 11, 3, 1, 1)
        self.load2 = QtWidgets.QPushButton(self.centralwidget)
        self.load2.setObjectName("load2")
        self.gridLayout.addWidget(self.load2, 8, 3, 1, 1)
        self.changed_img1 = QtWidgets.QLabel(self.centralwidget)
        self.changed_img1.setText("")
        self.changed_img1.setObjectName("changed_img1")
        self.gridLayout.addWidget(self.changed_img1, 1, 2, 1, 1)
        self.img1 = QtWidgets.QLabel(self.centralwidget)
        self.img1.setText("")
        self.img1.setObjectName("img1")
        self.gridLayout.addWidget(self.img1, 1, 3, 1, 1)
        self.combo_out = QtWidgets.QComboBox(self.centralwidget)
        self.combo_out.setObjectName("combo_out")
        self.combo_out.addItem("")
        self.combo_out.addItem("")
        self.gridLayout.addWidget(self.combo_out, 0, 0, 1, 1)
        self.comboReal3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboReal3.setMinimumSize(QtCore.QSize(660, 20))
        self.comboReal3.setObjectName("comboReal3")
        self.comboReal3.addItem("")
        self.comboReal3.addItem("")
        self.comboReal3.addItem("")
        self.comboReal3.addItem("")
        self.comboReal3.addItem("")
        self.comboReal3.addItem("")
        self.gridLayout.addWidget(self.comboReal3, 2, 0, 1, 1)
        self.Slider1 = QtWidgets.QSlider(self.centralwidget)
        self.Slider1.setOrientation(QtCore.Qt.Horizontal)
        self.Slider1.setObjectName("Slider1")
        self.gridLayout.addWidget(self.Slider1, 3, 0, 1, 1)
        self.choose_img1 = QtWidgets.QComboBox(self.centralwidget)
        self.choose_img1.setObjectName("choose_img1")
        self.choose_img1.addItem("")
        self.choose_img1.addItem("")
        self.gridLayout.addWidget(self.choose_img1, 1, 0, 1, 1)
        self.chooseReal4 = QtWidgets.QComboBox(self.centralwidget)
        self.chooseReal4.setObjectName("chooseReal4")
        self.chooseReal4.addItem("")
        self.chooseReal4.addItem("")
        self.chooseReal4.addItem("")
        self.chooseReal4.addItem("")
        self.chooseReal4.addItem("")
        self.chooseReal4.addItem("")
        self.gridLayout.addWidget(self.chooseReal4, 6, 0, 1, 1)
        self.load1 = QtWidgets.QPushButton(self.centralwidget)
        self.load1.setObjectName("load1")
        self.gridLayout.addWidget(self.load1, 5, 3, 1, 1)
        self.choose_img2 = QtWidgets.QComboBox(self.centralwidget)
        self.choose_img2.setObjectName("choose_img2")
        self.choose_img2.addItem("")
        self.choose_img2.addItem("")
        self.gridLayout.addWidget(self.choose_img2, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 3, 1, 1)
        self.output2 = QtWidgets.QLabel(self.centralwidget)
        self.output2.setText("")
        self.output2.setObjectName("output2")
        self.gridLayout.addWidget(self.output2, 10, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.load1.clicked.connect(MainWindow.getImage)
        self.load2.clicked.connect(MainWindow.getImage)
        self.comboReal1.activated['int'].connect(MainWindow.getMagnitude)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboReal2.setItemText(0, _translate("MainWindow", "Real"))
        self.comboReal2.setItemText(1, _translate("MainWindow", "Imagnire"))
        self.comboReal2.setItemText(2, _translate("MainWindow", "Phase "))
        self.comboReal2.setItemText(3, _translate("MainWindow", "Magnitude"))
        self.comboReal1.setItemText(0, _translate("MainWindow", "Real"))
        self.comboReal1.setItemText(1, _translate("MainWindow", "Imagnire"))
        self.comboReal1.setItemText(2, _translate("MainWindow", "Phase "))
        self.comboReal1.setItemText(3, _translate("MainWindow", "Magnitude"))
        self.load2.setText(_translate("MainWindow", "load img"))
        self.combo_out.setItemText(0, _translate("MainWindow", "Output1"))
        self.combo_out.setItemText(1, _translate("MainWindow", "Output2"))
        self.comboReal3.setItemText(0, _translate("MainWindow", "Real"))
        self.comboReal3.setItemText(1, _translate("MainWindow", "Imagnire"))
        self.comboReal3.setItemText(2, _translate("MainWindow", "Phase "))
        self.comboReal3.setItemText(3, _translate("MainWindow", "Magnitude"))
        self.comboReal3.setItemText(4, _translate("MainWindow", "uniform phase"))
        self.comboReal3.setItemText(5, _translate("MainWindow", "uniform magnitude "))
        self.choose_img1.setItemText(0, _translate("MainWindow", "Image1"))
        self.choose_img1.setItemText(1, _translate("MainWindow", "Image2"))
        self.chooseReal4.setItemText(0, _translate("MainWindow", "Real"))
        self.chooseReal4.setItemText(1, _translate("MainWindow", "Imagnire"))
        self.chooseReal4.setItemText(2, _translate("MainWindow", "Phase "))
        self.chooseReal4.setItemText(3, _translate("MainWindow", "Magnitude"))
        self.chooseReal4.setItemText(4, _translate("MainWindow", "uniform phase"))
        self.chooseReal4.setItemText(5, _translate("MainWindow", "uniform magnitude "))
        self.load1.setText(_translate("MainWindow", "load img"))
        self.choose_img2.setItemText(0, _translate("MainWindow", "Image1"))
        self.choose_img2.setItemText(1, _translate("MainWindow", "Image2"))
        self.label.setText(_translate("MainWindow", "Image1"))
        self.label_2.setText(_translate("MainWindow", "Image2"))

